builders:
  view_model_generator_builder:
    import: "package:flyme_generator/builder.dart"
    builder_factories: ["viewModelGeneratorBuilder"]
    # build_extensions: { ".dart": [".flyme.dart"] }
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    # build_to: source
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
  domain_registry_generator_builder:
    import: "package:flyme_generator/builder.dart"
    builder_factories: ["domainRegistryGeneratorBuilder"]
    build_extensions: { ".dart": [".registry.dart"] }
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  domain_instance_generator_builder:
    import: "package:flyme_generator/builder.dart"
    builder_factories: ["domainInstanceGeneratorBuilder"]
    build_extensions: { ".dart": [".instance.dart"] }
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  route_config_generator_builder:
    import: "package:flyme_generator/builder.dart"
    builder_factories: ["routeConfigGeneratorBuilder"]
    build_extensions: { ".dart": [".config.dart"] }
    #    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    # auto_apply: root_package
    #    build_to: cache
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  route_generator_builder:
    import: "package:flyme_generator/builder.dart"
    builder_factories: ["routeGeneratorBuilder"]
    build_extensions: { ".dart": [".route.dart"] }
    #    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    #    auto_apply: root_package
    #    build_to: cache
    build_to: source
    runs_before: ["flyme_generator|route_config_generator_builder"]
    applies_builders: ["source_gen|combining_builder"]
  functional_widget_generator_builder:
    import: "package:flyme_generator/builder.dart"
    builder_factories: ["functionalWidgetGeneratorBuilder"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

targets:
  $default:
    builders:
      flyme_generator|view_model_generator_builder:
        enabled: true
      flyme_generator|domain_registry_generator_builder:
        enabled: true
      flyme_generator|domain_instance_generator_builder:
        enabled: true
      flyme_generator|route_config_generator_builder:
        enabled: true
      flyme_generator|route_generator_builder:
        enabled: true
      flyme_generator|functional_widget_generator_builder:
        enabled: true
