name: flyme_generator
description: Generator from Flyme Framework. Flyme Framework is a cross-platform framework based on flutter.
version: 0.0.2
homepage: https://github.com/maybewaityou
documentation: https://github.com/maybewaityou/flyme_generator/blob/master/README.md
repository: https://github.com/maybewaityou/flyme_generator
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

#  flyme_annotation: ^0.0.3
  flyme_annotation:
    git: https://github.com/maybewaityou/flyme_annotation.git
  analyzer: ^0.39.4
  build: ^1.2.2
  build_config: ^0.4.1+1
  source_gen: ^0.9.4+7
  code_builder: ^3.2.1
  dart_style: ^1.3.3
  mustache_template: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.7.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
